baseURL = "http://camptocamp.github.io/infrastructure/"
title = "Infrastructure"
languageCode = "en-us"
theme = "elate"

[params]

  #custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Camptocamp"
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Infrastructure"
    #intro = "<i class='icon-home'></i>Install"
    #work = "<i class='icon-camera'></i>Screenshots"
    #testimonials = "<i class='icon-bubbles'></i>Testimonials"
    #services = "<i class='icon-star'></i>Features"
    about = "<i class='icon-bulb'></i>projects"
    contact = "<i class='icon-envelope'></i> Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

  # Hero section
  [params.hero]
    title = " <p>Open Source Infrastructure</p>"
    subtitle = '''
[![By Camptocamp](https://img.shields.io/badge/by-camptocamp-fb7047.svg)](http://www.camptocamp.com)
'''

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Global infrastructure"
    description = '''
We use and contribute to many Open Source tools.

![Camptocamp's Infrastructure](images/c2c_technos_pic.png)
'''
    icon = "icon-bulb"


  # About section
  [params.about]
    enable = true
    title = "Open Source projects"
    description = "We love to contribute Open Source projects at Camptocamp.<br /> Here is a list of some of our most useful tools"

    [[params.about.item]]
      name = "Terraboard"
      position = "A Web dashboard to inspect and query Terraform states"
      description = ""
      img = "terraboard.png"
      alt = "Terraboard"
      social = [
        ["icon-globe", "https://camptocamp.github.io/terraboard"],
        ["icon-github", "https://github.com/camptocamp/terraboard"]
      ]

    [[params.about.item]]
      name = "Conplicity"
      position = "Automatic backups for Docker containers"
      description = ""
      img = "conplicity.png"
      alt = "Conplicity"
      social = [
        ["icon-globe", "https://camptocamp.github.io/conplicity"],
        ["icon-github", "https://github.com/camptocamp/conplicity"]
      ]

    [[params.about.item]]
      name = "Puppet Modules"
      position = "Camptocamp's Puppet Modules"
      description = ""
      img = "puppet.png"
      alt = "Puppet Modules"
      social = [
        ["icon-globe", "https://camptocamp.github.io/puppet-modules"],
        ["icon-home", "https://forge.puppet.com/camptocamp"]
      ]

  # Contact section
  [params.contact]
    enable = true
    form = false
    title = "Contact us!"
    description = "Are you missing features? Would you like consulting, training or other services? Contact us at [info@camptocamp.com](mailto:info@camptocamp.com?subject=Terraboard)!"

  # Footer section
  [params.footer]
    enable = true
    copyright = '[![Camptocamp](images/camptocamp.png)](https://www.camptocamp.com)'
    links = [
        ["icon-globe", "https://www.camptocamp.com"],
        ["icon-twitter", "https://twitter.com/camptocamp"],
        ["icon-github", "https://github.com/camptocamp"]
      ]
